# Generated by Django 4.2.13 on 2025-03-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_partyVw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('mobile_num', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('Party_type', models.CharField(max_length=100)),
                ('party_category', models.CharField(max_length=100)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('credit_period', models.IntegerField(default=0)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
