# Generated by Django 5.0.6 on 2025-09-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_purchasereturn_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled'), ('PARTIALLY_RETURNED', 'Partially Returned'), ('FULLY_RETURNED', 'Fully Returned')], default='ORDERED', max_length=20),
        ),
    ]
