# Generated by Django 4.2.13 on 2025-03-23 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_create_partyvw'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Create_partyVw',
            new_name='Create_party',
        ),
    ]
