# Generated by Django 4.2.13 on 2025-03-23 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_create_partyvw_create_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_party',
            old_name='Party_type',
            new_name='party_type',
        ),
    ]
