# Generated by Django 5.0.6 on 2025-09-03 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_purchase_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('ADD', 'Add Stock'), ('REMOVE', 'Remove Stock')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged Goods'), ('STOLEN', 'Stolen Goods'), ('STOCKTAKE', 'Stocktake Correction'), ('INTERNAL_USE', 'Internal Use'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='backend.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='backend.tenant')),
            ],
        ),
    ]
