# Generated by Django 5.0.6 on 2025-08-06 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'User Logged In'), ('PARTY_ADD', 'Party Created'), ('ITEM_ADD', 'Item Created'), ('SALE_ADD', 'Sale Created'), ('SALE_DEL', 'Sale Deleted')], max_length=10)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.account')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
