# Generated by Django 4.2.13 on 2025-04-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_party_type_create_party_party_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_party',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.admin_login'),
        ),
    ]
