# Generated by Django 5.0.6 on 2025-09-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
