# Generated by Django 5.0.6 on 2025-08-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('FINANCIAL', 'Financial'), ('AUTH', 'Authentication')], default='GENERAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'User Logged In'), ('TENANT_ADD', 'Tenant Created'), ('ACC_ADD', 'Account Created'), ('ACC_EDIT', 'Account Edited'), ('PARTY_ADD', 'Party Created'), ('PARTY_EDIT', 'Party Edited'), ('PARTY_DEL', 'Party Deleted'), ('ITEM_ADD', 'Item Created'), ('SALE_ADD', 'Sale Created'), ('SALE_EDIT', 'Sale Edited'), ('SALE_DEL', 'Sale Deleted'), ('PAY_ADD', 'Payment Recorded')], max_length=10),
        ),
    ]
