# Generated by Django 4.2.13 on 2025-04-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_create_party_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_login',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
