# Generated by Django 5.0.6 on 2025-09-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_tenant_address_tenant_email_tenant_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_qr_codes/', verbose_name='UPI QR Code Image'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UPI ID'),
        ),
    ]
