# Generated by Django 5.0.6 on 2025-08-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_account_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'User Logged In'), ('TENANT_ADD', 'Tenant Created'), ('ACC_ADD', 'Account Created'), ('ACC_EDIT', 'Account Edited'), ('IMP_START', 'Impersonation Started'), ('IMP_STOP', 'Impersonation Stopped'), ('PARTY_ADD', 'Party Created'), ('PARTY_EDIT', 'Party Edited'), ('PARTY_DEL', 'Party Deleted'), ('ITEM_ADD', 'Item Created'), ('SALE_ADD', 'Sale Created'), ('SALE_EDIT', 'Sale Edited'), ('SALE_DEL', 'Sale Deleted'), ('PAY_ADD', 'Payment Recorded')], max_length=10),
        ),
    ]
