# Generated by Django 5.0.6 on 2025-07-09 06:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=10)),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst', models.CharField(blank=True, choices=[('', 'None'), ('5%', 'GST@5%'), ('12%', 'GST@12%'), ('18%', 'GST@18%'), ('28%', 'GST@28%')], max_length=5)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, verbose_name='HSN/SAC Code')),
                ('opening_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_date', models.DateField(blank=True, null=True)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('item_des', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.category')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit')),
            ],
        ),
    ]
