# Generated by Django 5.0.6 on 2025-09-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_tenant_account_no_tenant_bank_name_tenant_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Account Holder's Name"),
        ),
    ]
