# Generated by Django 5.0.6 on 2025-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_activitylog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_end_date',
            field=models.DateField(blank=True, help_text='The date the service validity ends.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_start_date',
            field=models.DateField(blank=True, help_text='The date the service validity begins.', null=True),
        ),
    ]
