# Generated by Django 5.0.6 on 2025-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_tenant_account_holder_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='create_party',
            unique_together={('tenant', 'party_name')},
        ),
        migrations.AlterField(
            model_name='create_party',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='create_party',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='create_party',
            name='mobile_num',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='create_party',
            name='party_category',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='create_party',
            name='party_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='create_party',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
