# Generated by Django 5.0.6 on 2025-07-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_create_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_item',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
