# Generated by Django 5.0.6 on 2025-08-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_service_service_end_date_service_service_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_end_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_start_date',
        ),
    ]
