# Generated by Django 5.0.6 on 2025-08-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_service_service_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_start_date',
            field=models.DateField(blank=True, help_text='The date the service validity begins.', null=True),
        ),
    ]
