# Generated by Django 5.0.6 on 2025-07-10 06:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_create_item_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('gst_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.category')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('itembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.itembase')),
                ('service_unit', models.CharField(blank=True, choices=[('HRS', 'Hours'), ('DAY', 'Days'), ('PCS', 'Pieces'), ('UNT', 'Unit')], max_length=10, null=True)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
            ],
            bases=('backend.itembase',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('itembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.itembase')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('opening_stock', models.PositiveIntegerField(default=0)),
                ('stock_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('min_stock_level', models.PositiveIntegerField(default=0)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit')),
            ],
            bases=('backend.itembase',),
        ),
    ]
