# Generated by Django 5.0.6 on 2025-09-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_create_party_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
