# Generated by Django 5.0.6 on 2025-07-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_sale_saleitem_delete_create_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='party',
        ),
        migrations.AddField(
            model_name='sale',
            name='party_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='party_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='party_name',
            field=models.CharField(default='Unknown Party', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='party_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
