# Generated by Django 5.0.6 on 2025-09-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_unit_unique_together_alter_unit_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='cname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='category',
            name='tenant',
        ),
    ]
