# Generated by Django 5.0.6 on 2025-10-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_category_unique_together_alter_category_cname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='subdomain',
        ),
    ]
