# Generated by Django 5.0.6 on 2025-11-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_account_groups_account_is_staff_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_type',
            field=models.CharField(choices=[('TAX_INVOICE', 'Tax Invoice'), ('BILL_OF_SUPPLY', 'Bill of Supply')], default='TAX_INVOICE', max_length=20),
        ),
    ]
