# Generated by Django 5.0.6 on 2025-12-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_sale_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cin_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Corporate Identity No. (CIN)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='fssai_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FSSAI / License No.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='signature_img',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_signatures/', verbose_name='Authorized Signature'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website URL'),
        ),
    ]
